name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push API
      run: |
        docker build -t elasaid/qr-code-app:api ./api
        docker push elasaid/qr-code-app:api

    - name: Build and Push Frontend
      run: |
        docker build -t elasaid/qr-code-app:frontend ./frontend
        docker push elasaid/qr-code-app:frontend

